name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test length of lines for displayability
      run: python3 test_lines.py flappy.txt
